FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/stream_prediction.py src/stream_prediction.py
COPY src/read_file.py src/read_file.py

CMD ["python", "src/stream_prediction.py"]
